const clientsData = [
  {
    type: 'professional',
    name: 'STE Client Example',
    isExempt: false,
    reference: 'CL-0001',
    exemptNumber: null,
    exemptExpiration: null,
    taxNumber: '00000/A/A/000',
    register: '',
    website: '',
    email: 'client1@email.com',
    mobile: '+216 55 000 000',
    phone: '+216 73 000 000',
    address: '4000 Sousse - TUNISIE',
    city: 'Sousse',
    postalCode: '4000',
    country: 'TN',
    isArchived: false,
    createdById: 1,
  },
  {
    type: 'professional',
    name: 'Société Example 2',
    isExempt: false,
    reference: 'CL-0002',
    exemptNumber: null,
    exemptExpiration: null,
    taxNumber: '000000B/B/B/000',
    register: '',
    website: '',
    email: '',
    mobile: '',
    phone: '',
    address: 'Rue Amilcar Tunisie',
    city: 'La Marsa',
    postalCode: '2076',
    country: 'TN',
    isArchived: false,
    createdById: 1,
  },
  {
    type: 'individual',
    name: 'John Doey',
    isExempt: false,
    reference: 'CL-0003',
    exemptNumber: '5487866623248418787848',
    exemptExpiration: '30-12-2023',
    taxNumber: null,
    register: '',
    website: '',
    email: '',
    mobile: '',
    phone: '',
    address: '',
    city: '',
    postalCode: '',
    country: 'TN',
    isArchived: false,
    createdById: 1,
  },
];

module.exports = clientsData;
