const productData = [
  {
    categoryId: 1,
    code: 'FAB001',
    label: 'Serge',
    description: '100% coton serge',
    price: 19.99,
    colorId: 10,
    quantity: 0,
    unitId: 1,
    minStock: 50,
    maxStock: 500,
    isArchived: false,
    vatId: 1,
    createdById: 1,
  },
  {
    categoryId: 1,
    code: 'FAB002',
    label: 'Coton Croisé',
    description: '100% coton croisé',
    price: 15.99,
    quantity: 0,
    unitId: 1,
    minStock: 30,
    maxStock: 300,
    isArchived: false,
    vatId: 1,
    createdById: 1,
  },
  {
    categoryId: 1,
    code: 'FAB003',
    label: 'Toile POLYCOTON',
    description: 'Toile en mélange POLYCOTON',
    price: 12.99,
    quantity: 250,
    unitId: 1,
    minStock: 40,
    maxStock: 400,
    isArchived: false,
    vatId: 1,
    createdById: 1,
  },
  {
    categoryId: 1,
    code: 'FAB004',
    label: 'Toile polyviscose',
    description: 'Toile en mélange polyviscose',
    price: 14.99,
    quantity: 180,
    unitId: 1,
    minStock: 35,
    maxStock: 350,
    isArchived: false,
    vatId: 1,
    createdById: 1,
  },
  {
    categoryId: 1,
    code: 'FAB005',
    label: 'Toile 100% COTON',
    description: 'Toile en 100% coton',
    price: 17.99,
    quantity: 220,
    unitId: 1,
    minStock: 45,
    maxStock: 450,
    isArchived: false,
    vatId: 1,
    createdById: 1,
  },
  {
    categoryId: 1,
    code: 'FAB006',
    label: 'TOILE 50%50%',
    description: 'Toile en mélange 50% coton, 50% polyester',
    price: 13.99,
    quantity: 190,
    unitId: 1,
    minStock: 25,
    maxStock: 250,
    isArchived: false,
    vatId: 1,
    createdById: 1,
  },
  {
    categoryId: 1,
    code: 'FAB007',
    label: '100% POLYESTER',
    description: 'Toile 100% polyester',
    price: 16.99,
    quantity: 240,
    unitId: 1,
    minStock: 55,
    maxStock: 550,
    isArchived: false,
    vatId: 1,
    createdById: 1,
  },
  {
    categoryId: 1,
    code: 'FAB008',
    label: 'NATTE',
    description: 'Natte en mélange',
    price: 18.99,
    quantity: 260,
    unitId: 1,
    minStock: 60,
    maxStock: 600,
    isArchived: false,
    vatId: 1,
    createdById: 1,
  },
  {
    categoryId: 1,
    code: 'FAB009',
    label: '100 % COTON MAILLE',
    description: '100% coton maille',
    price: 21.99,
    quantity: 180,
    colorId: 6,
    unitId: 1,
    minStock: 40,
    maxStock: 400,
    isArchived: false,
    vatId: 1,
    createdById: 1,
  },
  {
    categoryId: 1,
    code: 'FAB010',
    label: 'POLYAMIDE',
    description: 'Toile en polyamide',
    price: 23.99,
    quantity: 210,
    unitId: 1,
    minStock: 50,
    maxStock: 500,

    isArchived: false,
    vatId: 1,
    createdById: 1,
  },
  {
    categoryId: 8,
    code: 'GAR001',
    label: 'Serge',
    description: '100% coton serge',
    price: 19.99,
    colorId: 10,
    quantity: 0,
    unitId: 1,
    minStock: 50,
    maxStock: 500,
    isArchived: false,
    vatId: 1,
    createdById: 1,
  },
];

module.exports = productData;
