const supplierData = [
  {
    type: 'professional',
    name: 'Mohamed Ahmed',
    reference: 'FR-00',
    taxNumber: '00000C/C/000',
    register: '',
    website: '',
    email: '',
    mobile: '+216 24 000 000',
    phone: '',
    address: 'SFAX SAKIET EDDAIER, SFAX',
    city: '',
    postalCode: '',
    country: 'TN',
    isArchived: false,
    createdById: 1,
  },
  {
    type: 'professional',
    name: 'Samir Ben Hmida',
    reference: 'FR-01',
    taxNumber: '00000G/A/M000',
    register: '',
    website: '',
    email: '',
    mobile: '216 25 000 000',
    phone: '216 31 000 000',
    address: '',
    city: '',
    postalCode: '',
    country: 'TN',
    isArchived: false,
    createdById: 1,
  },
  {
    type: 'professional',
    name: 'Sté Fournisseur',
    reference: 'FR-00',
    taxNumber: '000000B/A/M/000',
    register: '',
    website: '',
    email: 'commercial@gmail.com',
    mobile: '216 20 000 000',
    phone: '216 55 000 000',
    address: 'HAMMAM SOUSSE, SOUSSE',
    city: '',
    postalCode: '',
    country: 'TN',
    isArchived: false,
    createdById: 1,
  },
  {
    type: 'professional',
    name: 'TEX',
    reference: 'FR-00',
    taxNumber: '00000X/A/M000',
    register: '',
    website: '',
    email: '',
    mobile: '',
    phone: '',
    address: '',
    city: '',
    postalCode: '',
    country: 'TN',
    isArchived: false,
    createdById: 1,
  },
  {
    type: 'professional',
    name: 'COTUTEX',
    reference: 'FR-00',
    taxNumber: '000000N/A/M/000',
    register: '',
    website: '',
    email: '',
    mobile: '216 56 000 000',
    phone: '216 54 000 000',
    address: 'KSAR HLEL',
    city: '',
    postalCode: '',
    country: 'TN',
    isArchived: false,
    createdById: 1,
  },
];

module.exports = supplierData;
